### PR TITLE
Localized sounds should be mono, not stereo.

### PR DESCRIPTION
**Pull request by sofar**
Stereo sounds are unattenuated, thus way too loud too far. Converting
them to mono also makes them almost twice as small.

### CODE REVIEW

**Comment by HybridDog** [comment]
l recently saw that sounds became converted from 44.1 kHz to 22.05 kHz.
When l played sauerbraten l noticed that 22050 audibly decreases the quality of the music (l couldn't hear the high frequency noises).

**Comment by sofar** [comment]
thanks, I'll try to keep them at 44.1 kHz when I do these.

**Comment by sofar** [comment]
@HybridDog btw since the old files are in git, we can always recover and put the 44.1kHz sounds back.

**Comment by HybridDog** [comment]
the disadvantage is that cloning the repository takes longer because every file in history becomes downloaded, there should be the possibility to set dummies instead of downloading them

**Pull request closed without merging**
